services:
  - type: worker
    name: insta-telegram-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: POST_URL
        sync: false
      - key: TELEGRAM_MESSAGE_TEMPLATE
        sync: false
